In [4]:
import numpy as np  # Importa a biblioteca NumPy para seu projeto
import timeit   

## Exercicio 8


In [5]:
iris_dataset_url = 'https://archive.ics.uci.edu/ml/machine-learning-databases/iris/iris.data'

In [6]:
iris = np.genfromtxt(iris_dataset_url, delimiter = ',', dtype = 'object', encoding='ascii')

In [44]:
iris[:3]

array([[b'5.1', b'3.5', b'1.4', b'0.2', b'Iris-setosa'],
       [b'4.9', b'3.0', b'1.4', b'0.2', b'Iris-setosa'],
       [b'4.7', b'3.2', b'1.3', b'0.2', b'Iris-setosa']], dtype=object)

## Exercicio 9
Extraia a coluna species do dataset importado na questão anterior para um vetor unidimensional.

In [55]:
species = np.expand_dims(iris[:, 4], axis = 1)
species[:4]

array([[b'Iris-setosa'],
       [b'Iris-setosa'],
       [b'Iris-setosa'],
       [b'Iris-setosa']], dtype=object)

## Exercicio 10
Calcule a média, mediana e desvio padrão da primeira coluna (sepallength) do dataset Iris.

In [93]:
sepal_length = np.expand_dims(iris[:, 0], axis = 1)
sepal_length[:4]

sepal_length_int = sepal_length.astype('float')

media = np.mean(sepal_length_int)
mediana = np.median(sepal_length_int)
desvio_padrao = sepal_length_int.std()

print(media)
print(mediana)
print(desvio_padrao)


5.843333333333334
5.8
0.8253012917851409


## Exercicio 11
Normalize a coluna (sepallength) do dataset iris de tal forma que o valor mínimo seja zero (0) e o valor máximo seja 1.


In [110]:
sepal_length_normalizado = (sepal_length_int - sepal_length_int.min())/(sepal_length_int.max()- sepal_length_int.min())
sepal_length_normalizado[:4]
print("Minimo: " + str(sepal_length_normalizado.min()))
print("Máximo: " + str(sepal_length_normalizado.max()))

Minimo: 0.0
Máximo: 1.0


## Exercicio 12
Encontre o 5º e o 95º percentil do comprimento das pétalas (sepallength) do dataset Iris.

In [115]:
print(np.percentile(sepal_length_int, 5))
print(np.percentile(sepal_length_int, 95))

4.6
7.254999999999998


## Exercicio 13
Encontre a quantidade de valores ausentes, bem como a posição deles da primeira coluna da coluna comprimento das pétalas (sepallength), dentro do vetor abaixo:


In [154]:
url = 'https://archive.ics.uci.edu/ml/machine-learning-databases/iris/iris.data' 
iris_2d = np.genfromtxt(url, delimiter=',', dtype='float') 
iris_2d[np.random.randint(150, size=20), np.random.randint(4, size=20)] = np.nan

In [125]:
np.isnan(iris_2d[:,0])
print(np.isnan(iris_2d[:,0]).sum())
print(np.where(np.isnan(iris_2d[:,0])))

5
(array([  9,  38,  74,  87, 114], dtype=int64),)


## Exercicio 14
Filtre o vetor iris_2d do exercício anterior para que ele tenha: (terceira coluna (petallength) > 1.5) && (primeira coluna (sepallength) < 5.0)


In [151]:
filtro = (iris_2d[:,2] > 1.5) & (iris_2d[:,0] < 5)
iris_2d[filtro]

array([[4.8, 3.4, 1.6, 0.2],
       [4.8, 3.4, 1.9, 0.2],
       [4.7, 3.2, 1.6, 0.2],
       [4.8, 3.1, 1.6, 0.2],
       [4.9, 2.4, 3.3, 1. ],
       [4.9, 2.5, 4.5, 1.7]])

## Exercicio 15
Selecione as linhas do vetor iris_2d que não contenham valores nan (Not a Number).

In [129]:
print(np.where(np.isnan(iris_2d[:,0]) == False))

(array([  0,   1,   2,   3,   4,   5,   6,   7,   8,  10,  11,  12,  13,
        14,  15,  16,  17,  18,  19,  20,  21,  22,  23,  24,  25,  26,
        27,  28,  29,  30,  31,  32,  33,  34,  35,  36,  37,  39,  40,
        41,  42,  43,  44,  45,  46,  47,  48,  49,  50,  51,  52,  53,
        54,  55,  56,  57,  58,  59,  60,  61,  62,  63,  64,  65,  66,
        67,  68,  69,  70,  71,  72,  73,  75,  76,  77,  78,  79,  80,
        81,  82,  83,  84,  85,  86,  88,  89,  90,  91,  92,  93,  94,
        95,  96,  97,  98,  99, 100, 101, 102, 103, 104, 105, 106, 107,
       108, 109, 110, 111, 112, 113, 115, 116, 117, 118, 119, 120, 121,
       122, 123, 124, 125, 126, 127, 128, 129, 130, 131, 132, 133, 134,
       135, 136, 137, 138, 139, 140, 141, 142, 143, 144, 145, 146, 147,
       148, 149], dtype=int64),)


## Exercicio 16
Encontre a correlação entre a primeira coluna (sepallength) e a (terceira coluna (petallength) no vetor iris_2d.

In [136]:
url = 'https://archive.ics.uci.edu/ml/machine-learning-databases/iris/iris.data'
iris_3d = np.genfromtxt(url, delimiter=',', dtype='float', usecols=[0,1,2,3])

In [153]:
np.corrcoef(iris_3d[:,0],iris_3d[:,2])

array([[1.        , 0.87175416],
       [0.87175416, 1.        ]])

## Exercicio 17
Verifique se o vetor iris_2d possui qualquer valor faltante, caso possui deverá retornar True caso contrário False.

In [140]:
def VerificaNulo(vetor):
    contador = np.isnan(vetor).sum()
    if contador == 0:
        return False
    else:
        return True

VerificaNulo(iris_3d)

False

# Exercicio 18
Substitua todas as ocorrências de nan (Not a Number) por zeros em um vetor NumPy.

In [141]:
url = 'https://archive.ics.uci.edu/ml/machine-learning-databases/iris/iris.data'
iris_2d = np.genfromtxt(url, delimiter=',', dtype='float', usecols=[0,1,2,3])

In [155]:
VerificaNulo(iris_2d)

True

In [156]:
np.where(np.isnan(iris_2d[:,0]) == True)

(array([ 3, 35, 40, 59, 77, 81, 95], dtype=int64),)

In [157]:
filtro = np.isnan(iris_2d[:,0]) == True
iris_2d[filtro]

array([[nan, 3.1, 1.5, 0.2, nan],
       [nan, 3.2, 1.2, 0.2, nan],
       [nan, 3.5, 1.3, nan, nan],
       [nan, 2.7, 3.9, 1.4, nan],
       [nan, 3. , 5. , 1.7, nan],
       [nan, 2.4, 3.7, 1. , nan],
       [nan, 3. , 4.2, 1.2, nan]])


# Exercicio 19
Encontre e conte os valores únicos da coluna species




In [7]:
iris_2d = np.genfromtxt('https://archive.ics.uci.edu/ml/machine-learning-databases/iris/iris.data', delimiter=',', dtype='object')

print(np.unique(iris_2d[:,4]))

[b'Iris-setosa' b'Iris-versicolor' b'Iris-virginica']


# Exercicio 20
Mapeie terceira coluna (petallength) de tal forma que os valores numéricos sejam substituídos por valores textuais, seguindo de acordo com a tabela abaixo:
Númer -- Classificação
Menor do que 3--Pequena
entre 3 e 5 -- Média
Maior ou Igual a 5--Grande

In [9]:
iris_2d = np.genfromtxt('https://archive.ics.uci.edu/ml/machine-learning-databases/iris/iris.data', delimiter=',', dtype='object')
petallength = np.array(iris_2d[:,2], dtype='float')

for i, item in enumerate(petallength):
    if (item < 3):
        iris_2d[i][2] = "Pequena"
    elif (item >= 3 and item < 5):
        iris_2d[i][2] = "Média"
    else:
        iris_2d[i][2] = "Grande"
iris_2d  

array([[b'5.1', b'3.5', 'Pequena', b'0.2', b'Iris-setosa'],
       [b'4.9', b'3.0', 'Pequena', b'0.2', b'Iris-setosa'],
       [b'4.7', b'3.2', 'Pequena', b'0.2', b'Iris-setosa'],
       [b'4.6', b'3.1', 'Pequena', b'0.2', b'Iris-setosa'],
       [b'5.0', b'3.6', 'Pequena', b'0.2', b'Iris-setosa'],
       [b'5.4', b'3.9', 'Pequena', b'0.4', b'Iris-setosa'],
       [b'4.6', b'3.4', 'Pequena', b'0.3', b'Iris-setosa'],
       [b'5.0', b'3.4', 'Pequena', b'0.2', b'Iris-setosa'],
       [b'4.4', b'2.9', 'Pequena', b'0.2', b'Iris-setosa'],
       [b'4.9', b'3.1', 'Pequena', b'0.1', b'Iris-setosa'],
       [b'5.4', b'3.7', 'Pequena', b'0.2', b'Iris-setosa'],
       [b'4.8', b'3.4', 'Pequena', b'0.2', b'Iris-setosa'],
       [b'4.8', b'3.0', 'Pequena', b'0.1', b'Iris-setosa'],
       [b'4.3', b'3.0', 'Pequena', b'0.1', b'Iris-setosa'],
       [b'5.8', b'4.0', 'Pequena', b'0.2', b'Iris-setosa'],
       [b'5.7', b'4.4', 'Pequena', b'0.4', b'Iris-setosa'],
       [b'5.4', b'3.9', 'Pequena', b'0.4

## Exercicio 21
Crie uma nova coluna chamada volume, preenchida com dados resultantes da seguinte equação:
$$volume=\frac{(~ Pi ~x~ Petallength ~x~ Sepal Length^2 ~)}{3}$$

In [13]:
iris_2d = np.genfromtxt('https://archive.ics.uci.edu/ml/machine-learning-databases/iris/iris.data', delimiter=',', dtype='object')
volume = []
petallength = np.array(iris_2d[:,2], dtype='float')
sepallength = np.array(iris_2d[:,2], dtype='float')

for i, item in enumerate(petallength):
    volume.append((np.pi*item* pow(sepallength[i],2)/3))
    
iris_2d_volume = np.c_[np.array(iris_2d), np.array(volume)]
    
iris_2d_volume

array([[b'5.1', b'3.5', b'1.4', b'0.2', b'Iris-setosa',
        2.8735100804834635],
       [b'4.9', b'3.0', b'1.4', b'0.2', b'Iris-setosa',
        2.8735100804834635],
       [b'4.7', b'3.2', b'1.3', b'0.2', b'Iris-setosa',
        2.3006930199789255],
       [b'4.6', b'3.1', b'1.5', b'0.2', b'Iris-setosa',
        3.5342917352885173],
       [b'5.0', b'3.6', b'1.4', b'0.2', b'Iris-setosa',
        2.8735100804834635],
       [b'5.4', b'3.9', b'1.7', b'0.4', b'Iris-setosa',
        5.144881569028883],
       [b'4.6', b'3.4', b'1.4', b'0.3', b'Iris-setosa',
        2.8735100804834635],
       [b'5.0', b'3.4', b'1.5', b'0.2', b'Iris-setosa',
        3.5342917352885173],
       [b'4.4', b'2.9', b'1.4', b'0.2', b'Iris-setosa',
        2.8735100804834635],
       [b'4.9', b'3.1', b'1.5', b'0.1', b'Iris-setosa',
        3.5342917352885173],
       [b'5.4', b'3.7', b'1.5', b'0.2', b'Iris-setosa',
        3.5342917352885173],
       [b'4.8', b'3.4', b'1.6', b'0.2', b'Iris-setosa',
        4.

## Exercicio 22
Usando NumPy e o dataset iris responda: Qual é o segundo maior valor de comprimento de pétala (petallength) da espécie setosa?

In [14]:
condicao = (iris_2d[:,4] == b'Iris-setosa')

iris_2d_setosa = iris_2d[condicao]
petallength = np.unique(np.sort(iris_2d_setosa[:,2]))

print(str(petallength[len(petallength)-2]))

b'1.7'


## Exercicio 23
Ordene o dataset iris com base na coluna sepallength de maneira crescente

In [15]:
dtype = [('sepallength', float), ('sepalwidth', float), ('petallength', float), ('petalwidth', float), ('species', 'S20')]
iris_2d = np.genfromtxt('https://archive.ics.uci.edu/ml/machine-learning-databases/iris/iris.data', delimiter=',', dtype=dtype)       
np.sort(iris_2d, order='sepallength')

array([(4.3, 3. , 1.1, 0.1, b'Iris-setosa'),
       (4.4, 2.9, 1.4, 0.2, b'Iris-setosa'),
       (4.4, 3. , 1.3, 0.2, b'Iris-setosa'),
       (4.4, 3.2, 1.3, 0.2, b'Iris-setosa'),
       (4.5, 2.3, 1.3, 0.3, b'Iris-setosa'),
       (4.6, 3.1, 1.5, 0.2, b'Iris-setosa'),
       (4.6, 3.2, 1.4, 0.2, b'Iris-setosa'),
       (4.6, 3.4, 1.4, 0.3, b'Iris-setosa'),
       (4.6, 3.6, 1. , 0.2, b'Iris-setosa'),
       (4.7, 3.2, 1.3, 0.2, b'Iris-setosa'),
       (4.7, 3.2, 1.6, 0.2, b'Iris-setosa'),
       (4.8, 3. , 1.4, 0.1, b'Iris-setosa'),
       (4.8, 3. , 1.4, 0.3, b'Iris-setosa'),
       (4.8, 3.1, 1.6, 0.2, b'Iris-setosa'),
       (4.8, 3.4, 1.6, 0.2, b'Iris-setosa'),
       (4.8, 3.4, 1.9, 0.2, b'Iris-setosa'),
       (4.9, 2.4, 3.3, 1. , b'Iris-versicolor'),
       (4.9, 2.5, 4.5, 1.7, b'Iris-virginica'),
       (4.9, 3. , 1.4, 0.2, b'Iris-setosa'),
       (4.9, 3.1, 1.5, 0.1, b'Iris-setosa'),
       (4.9, 3.1, 1.5, 0.1, b'Iris-setosa'),
       (4.9, 3.1, 1.5, 0.1, b'Iris-setosa'),
   

## Exercicio 24
Encontre o valor mais frequente da terceira coluna (petallength) do dataset iris.

In [16]:
iris_2d = np.genfromtxt('https://archive.ics.uci.edu/ml/machine-learning-databases/iris/iris.data', delimiter=',', dtype='object')
valores, contador = np.unique(iris_2d[:,2], return_counts=True)
posicao = np.where(contador == contador.max())
print(str(valores[int(posicao[0])]))

b'1.5'


## Exercicio 25
Encontre a posição da primeira ocorrência de um valor maior do que 1.0 da quarta coluna (petalwidth) do dataset iris.

In [17]:
iris_2d = np.genfromtxt('https://archive.ics.uci.edu/ml/machine-learning-databases/iris/iris.data', delimiter=',', dtype='float', usecols=[0,1,2,3])
posicao = np.where(iris_2d[:,3] > 1)
array = list(posicao[0])
print(str(int(array[0])))

50


## Exercicio 26
Obtenha a posição dos top 5 valores maíximos do vetor abaixo:

In [18]:
np.random.seed(100)
vetor = np.random.uniform(1,50, 20)
print(vetor[np.argsort(vetor)[-5:]])

[40.99501269 41.466785   42.39403048 44.67477576 48.95256545]


## Exercicio 27
Encontre a média de uma coluna numérica agrupada por uma coluna categórica em uma matriz (vetor numpy 2D)

In [19]:

iris_2d = np.genfromtxt('https://archive.ics.uci.edu/ml/machine-learning-databases/iris/iris.data', delimiter=',', dtype='object')
iris_2d_setosa = iris_2d[iris_2d[:,4]==b'Iris-setosa']
iris_2d_versicolor = iris_2d[iris_2d[:,4]==b'Iris-versicolor']
iris_2d_virginica = iris_2d[iris_2d[:,4]==b'Iris-virginica']
sepallength_setosa = np.array(iris_2d_setosa[:,0], dtype='float')
sepallength_versicolor = np.array(iris_2d_versicolor[:,0], dtype='float')
sepallength_virginica = np.array(iris_2d_virginica[:,0], dtype='float')
species = np.array([b'Iris-setosa', b'Iris-versicolor', b'Iris-virginica'])
media = np.array([sepallength_setosa.mean(), sepallength_versicolor.mean(), sepallength_virginica.mean()])
print(np.c_[species, media])

[[b'Iris-setosa' b'5.006']
 [b'Iris-versicolor' b'5.936']
 [b'Iris-virginica' b'6.587999999999998']]
